#!/bin/bash

status=$(quodlibet --status 2> /dev/null | awk '{print $1}')

if [[ "$status" == "playing" ]]
then
    echo $(quodlibet --print-playing '<artist> - <title>')
    exit 0
elif [[ "$status" == "paused" ]]
then
    echo \($(quodlibet --print-playing '<artist> - <title>')\)
    exit 0
else
    echo ""
    exit 0
fi

exit 0
